{
	"status":true,
	"apisite":"https:\/\/raw.githubusercontent.com\/rachitkataria13\/api\/master",
	"name1":"Please Don't Misuse It",
	"statusmain":true,
	"messmain":"Something may have went wrong please restart",
	"statuscall":false,
	"messcall":"Due to some reason Call api is not working i will push the notification after fixing This",
	"name2":"With the help of Hardiksinh",
	"errorb":false,
	"errorm":"Not Authorised to use this app",
	"customstatus":true,
	"custommsg":"Server Found But Files Didnt Match",
	"offer":"Initial Launch offer 12 month plan only at Rs 100 for first 100",
	"statuscall2":true,
	"messcall2":"Due to some reason Call api is not working i will push the notification after fixing This",
	"ads":0,
	"ads2":0,
	"anonytext":"Try Our New App ThumbzUP",
	"anonyurl":"http:\/\/thumbzup.me",
	"navanonycall":false,
	"navanonysms":false,
	"navcallblast":false,
	"navcallblastserv":false,
	"capi1":"aHR0cDovL2NhbGwefghucmpib21iZXIub29vL2luZGV4LnBocD9jPTEmaG09",
	"cooktest":"X190ZXN0PTZjY2M2NjBjYzk3MzYefgh1ZTMzNTRlY2NiNDdiNjg2Y2Yz",
	"numtextprotect":"Protection List Will Be Cleared after Every 3 Weeks.",
	"emailtextprotect":"Protection List Will Be Cleared after Every 3 Weeks.",
	"alertnotification":{
		"alerttitle":"Protection Clear New Schedule.",
		"alertmessage":"From Now Onwards Protection List Will Be Cleared Between 3-4 weeks every Month.",
		"alertid":0,
		"alertlink":"null"
	},
	"limo":999
}
